spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?setUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    database: 8
    password:

server:
  port: 9876

mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration: # 数据库下划线转驼峰配置
    mapUnderscoreToCamelCase: true
    jdbc-type-for-null: 'null'
    local-cache-scope: statement

lockeeper:
  a: 1
  b: 2
  c: 3